### ISSUE TITLE
Can't Import `microscopes.irm.query`

### ISSUE THREAD

**Issue by jzf2101** [datamicroscopes/irm#2]
@stephentu not sure what would be causing this - i get an error from the version i installed from conda

**Comment by tdhopper** [comment]
I'm trying to create a new conda release as @stephentu recommended, however I'm not sure that it'll work (because IRM hasn't changed since the last release I did). You don't have this problem if you build IRM?

**Comment by tdhopper** [comment]
@jzf2101 Can you try again with `conda install -f`?

**Comment by jzf2101** [comment]
trying to install the irm?

**Comment by jzf2101** [comment]
@tdhopper got the same error

**Comment by tdhopper** [comment]
I think it's fixed [here](https://github.com/datamicroscopes/release/commit/d0aad6500d07bbb97877af2101d0221dc25bdd1c). _I didn't read the directions_ and was only updating Binstar for Linux, not OS X.

Please let me know if you have problems, @jzf2101

**Comment by Sandy4321** [comment]
will it work for Windows?

**Comment by tdhopper** [comment]
@Sandy4321 No.

**Comment by Sandy4321** [comment]
why?
even on one core?

**Comment by Sandy4321** [comment]
by the way 
thank you very much for LDA explained youtube video
https://www.youtube.com/watch?v=_R66X_udxZQ&t=5s
Timothy Hopper: Understanding Probabilistic Topic Models By Simulation
may you share the link on the same high quality of explaining how to write simple python code to train LDA model, pls

**Comment by tdhopper** [comment]
@Sandy4321 It was too hard to build the C++ dependencies for Windows. Feel free to try to create your own build.

**Comment by Sandy4321** [comment]
by the way
thank you very much for LDA explained youtube video
https://www.youtube.com/watch?v=_R66X_udxZQ&t=5s
Timothy Hopper: Understanding Probabilistic Topic Models By Simulation
may you share the link on the same high quality of explaining how to write simple python code to train LDA model, pls
